version: '3.8'
services:
  stats-server:
    build: ./explore-statistic
    container_name: explore-statistic
    ports:
      - "9090:9090"
    depends_on:
      - "stats-db"

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "6542:5432"

  ewm-service:
    build: ./explore-main
    container_name: explore-main
    depends_on:
      - "ewm-db"
    ports:
      - "8080:8080"

  ewm-db:
    container_name: main-db
    image: postgres:14-alpine
    ports:
      - "6541:5432"