version: '3.8'
services:

  stats-server:
    build: ./explore-statistic
    container_name: explore-statistic
    ports:
      - "9090:9090"
    depends_on:
      - "stats-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreit

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=exploreit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./explore-main
    container_name: explore-main
    depends_on:
      - "ewm-db"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreit
      - EXPLOREIT-STAT-SERVER_URL=http://stats-server:9090

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=exploreit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root